server:
  port: 8081

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  config:                  #配置文件目录
    location: /config/
  profiles:                #分环境，java -jar --spring.profiles.active=prod激活
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: org.kxw.bms.auth.engity
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    use-generated-keys: true
