language: java

jdk:
- oraclejdk8

services:
- mysql

cache:
  directories:
  - .autoconf
  - $HOME/.m2

branches:
  only:
  - master

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS bms;'

script:
- 'sh deploy.sh'